spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:

       ddl-auto: validate #create-drop validate create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_suppointspb
    username: root
    password: root
  flyway:
    baseline-on-migrate: true